services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

    volumes:
      - ./pgdata:/var/lib/postgresql/data

  evolution-api:
    image: evoapicloud/evolution-api:v2.3.7
    container_name: evolution_api_mas_obi
    restart: always

    network_mode: "host"

    volumes:
      - ./instances:/evolution/instances

    env_file:
      - ./.env

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always

    network_mode: "host"

    volumes:
      - ./.n8n:/home/node/.n8n
      - ./.n8n-files:/home/node/.n8n-files

    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_FEATURE_FLAG_MCP=true
